{% set name = "smi-analysis" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smi-analysis-{{ version }}.tar.gz
  sha256: a9c4e786ec2e8c0eca4136b4b685a5027419b6b49f46c7db2f740fbfa0bc1f64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - h5py
    - numpy
    - pyfai
    - pygix >=2022.11.14
    - scipy
    - xarray

test:
  imports:
    - smi_analysis
    - smi_analysis.tests
  commands:
    - pytest --pyargs smi_analysis.tests
  requires:
    - pytest

about:
  home: https://github.com/NSLS-II-SMI/smi-analysis
  summary: Scientific Python for data analysis at the Soft Matter Interface (SMI) beamline at NSLS-II
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
    - gfreychet
